version: "3"
services:
  db:
    image: postgres:15
    container_name: url-shortener-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: url-shortener-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    command: ["sh", "-c", "npm run migration:run && npm run start:dev"]
    working_dir: /app
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: url-shortener-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next/cache
    command: npm run dev

volumes:
  pgdata:
